import assert from "node:assert/strict";
import { GameEngine, createInitialState } from "../src/game/engine";

const state = createInitialState({ name: "Window regression", avatar: "a1", lang: "fr", createdAt: 1 });
const engine = new GameEngine(state);
let published = 0;
const unsubscribe = engine.subscribe(() => { published += 1; });
engine.openApp("terminal");
engine.openApp("mail");
const beforeFocus = published;
engine.focusWindow("terminal");
assert.equal(published, beforeFocus + 1, "Window activation must notify React immediately");
assert.equal(engine.getState().activeWindow, "terminal");
engine.minimizeWindow("terminal");
assert.equal(engine.state.activeWindow, null);
assert(engine.state.openWindows.includes("terminal"), "Minimize keeps the app open");
engine.focusWindow("terminal");
engine.execTerminal("sudo nano /etc/resolv.conf", "WS-001");
assert(engine.state.editorOpen);
const beforeCancel = published;
engine.cancelEdit();
assert.equal(engine.state.editorOpen, null);
assert.equal(published, beforeCancel + 1, "Cancel must update immediately");
engine.execTerminal("whoami", "WS-001");
const history = [...engine.state.terminalHistory["WS-001"]];
engine.closeWindow("terminal");
assert.equal(engine.state.activeWindow, "mail");
engine.openApp("terminal");
assert.deepEqual(engine.state.terminalHistory["WS-001"], history);
const beforeMail = engine.state.mails;
const beforeChat = engine.state.chat;
engine.tick();
assert.notEqual(engine.state.mails, beforeMail, "Memoized apps receive a new snapshot");
assert.notEqual(engine.state.chat, beforeChat);
unsubscribe();
console.log("Window state, immediate subscriptions, editor dismissal and history: PASSED");
