import assert from "node:assert/strict";
import { GameEngine, createInitialState } from "../src/game/engine";
import { restoreWorkspace, defaultWindowLayout } from "../src/game/workspace";
import { resizedLayout, windowRect } from "../src/components/game/window-geometry";
import type { GameState } from "../src/game/types";

const initial = createInitialState({ name: "Workspace regression", avatar: "a1", lang: "fr", createdAt: 1 });
initial.xp = 275;
initial.skills.dns = { level: "practice", xp: 30, attempts: 2, successes: 1 };
initial.world.hosts["WS-001"].dns = ["10.0.0.10"];
const legacy = JSON.parse(JSON.stringify(initial)) as GameState;
delete (legacy as Partial<GameState>).workspace;
const progress = JSON.stringify({ world: legacy.world, xp: legacy.xp, skills: legacy.skills, missions: legacy.missions });
const engine = new GameEngine(legacy);
assert.equal(JSON.stringify({ world: engine.state.world, xp: engine.state.xp, skills: engine.state.skills, missions: engine.state.missions }), progress, "Loading an older save never replaces progress or the world");
assert.equal(engine.state.workspace.terminal.hostId, "WS-001");
engine.openApp("terminal");
engine.execTerminal("whoami", "WS-001");
engine.setTerminalDraft("WS-001", "ping intranet.horizon");
engine.selectTerminalHost("PC-MARIE");
engine.setTerminalDraft("PC-MARIE", "ip addr");
engine.setChatDraft("itsupport", "Diagnostic en cours");
engine.setChatDraft("soc", "Autre brouillon");
engine.selectChatChannel("soc");
engine.setWindowLayout("terminal", { x: 10, y: 12, width: 790, height: 470, maximized: false });
const roundtrip = new GameEngine(JSON.parse(JSON.stringify(engine.state)));
assert.equal(roundtrip.state.workspace.terminal.hostId, "PC-MARIE");
assert.equal(roundtrip.state.workspace.terminal.sessions["WS-001"].draft, "ping intranet.horizon");
assert.equal(roundtrip.state.workspace.terminal.sessions["PC-MARIE"].draft, "ip addr");
assert.equal(roundtrip.state.workspace.chat.channel, "soc");
assert.equal(roundtrip.state.workspace.chat.drafts.itsupport, "Diagnostic en cours");
assert.equal(roundtrip.state.workspace.terminal.sessions["WS-001"].blocks[0].output[0], "student");
assert.equal(roundtrip.state.terminalHistory["WS-001"].length, 1, "Restoring scrollback must never execute commands again");
assert.equal(roundtrip.state.xp, engine.state.xp);
roundtrip.execTerminal("sudo nano /etc/resolv.conf", "WS-001");
roundtrip.setEditorDraft("WS-001", "/etc/resolv.conf", "nameserver 172.16.0.99\n");
const editor = new GameEngine(JSON.parse(JSON.stringify(roundtrip.state)));
assert.equal(editor.state.workspace.editorDraft?.content, "nameserver 172.16.0.99\n");
assert.deepEqual(editor.state.world.hosts["WS-001"].dns, ["10.0.0.10"], "Drafts are not configuration changes");
editor.cancelEdit();
assert.equal(editor.state.workspace.editorDraft, null);
assert.deepEqual(editor.state.world.hosts["WS-001"].dns, ["10.0.0.10"]);
const stored = editor.state.workspace.windows.terminal!;
const mobile = windowRect(stored, { width: 350, height: 520 });
assert.equal(mobile.width, 350);
assert.equal(stored.width, 790, "A narrow viewport must not overwrite the saved desktop size");
const back = windowRect(stored, { width: 1200, height: 800 });
assert.equal(back.width, 790);
assert.equal(back.height, 470);
const shrunk = resizedLayout(back, -10000, -10000, { width: 1200, height: 800 });
assert.equal(shrunk.width, 460);
assert.equal(shrunk.height, 320);
const expanded = resizedLayout(back, 10000, 10000, { width: 1200, height: 800 });
assert.equal(expanded.width, 1190);
assert.equal(expanded.height, 788);
editor.resetWindowLayout("terminal");
assert.equal(editor.state.workspace.windows.terminal, undefined);
assert.equal(editor.state.workspace.chat.drafts.itsupport, "Diagnostic en cours");
const invalid = restoreWorkspace({
  windows: { terminal: { x: -50, width: Number.NaN, height: Infinity, maximized: "true" } },
  terminal: { hostId: "bad-host", sessions: { "WS-001": { draft: "a".repeat(1000), blocks: [{ command: {}, output: [] }] } } },
  chat: { channel: "missing", drafts: { soc: false } },
}, ["WS-001"]);
assert.deepEqual(invalid.windows.terminal, { ...defaultWindowLayout(), x: 0 });
assert.equal(invalid.terminal.hostId, "WS-001");
assert.equal(invalid.terminal.sessions["WS-001"].draft.length, 300);
assert.equal(invalid.terminal.sessions["WS-001"].blocks.length, 0);
assert.equal(invalid.chat.channel, "itsupport");
console.log("PASS: additive saves, drafts, editor recovery, bounded geometry and invalid workspace data.");
